apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-k7yj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-foqt-tenant/rhtap-demo-app/hacbs-test-project-k7yj@sha256:dc8758feee5164622741bcdd1f2d84a8fb6f4b3fd5bcc8cf35f72287cb7d67da
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
