apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-k7yj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-k7yj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-k7yj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-k7yj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-k7yj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-foqt-tenant/rhtap-demo-app/hacbs-test-project-k7yj@sha256:dc8758feee5164622741bcdd1f2d84a8fb6f4b3fd5bcc8cf35f72287cb7d67da
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
